//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you wish to delete this employee?.
        /// </summary>
        internal static string ConfirmDeleteMessageText {
            get {
                return ResourceManager.GetString("ConfirmDeleteMessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Employee Deletion.
        /// </summary>
        internal static string ConfirmDeleteMessageTop {
            get {
                return ResourceManager.GetString("ConfirmDeleteMessageTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application couldn&apos;t establish a connection to the database. Please check your internet connection or contact the help desk..
        /// </summary>
        internal static string DatabaseError {
            get {
                return ResourceManager.GetString("DatabaseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The branch cannot be empty.
        /// </summary>
        internal static string EmployeeBranchError {
            get {
                return ResourceManager.GetString("EmployeeBranchError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The e-mail address cannot be empty.
        /// </summary>
        internal static string EmployeeEmailError {
            get {
                return ResourceManager.GetString("EmployeeEmailError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first name cannot be empty.
        /// </summary>
        internal static string EmployeeFirstNameError {
            get {
                return ResourceManager.GetString("EmployeeFirstNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The last name cannot be empty.
        /// </summary>
        internal static string EmployeeLastNameError {
            get {
                return ResourceManager.GetString("EmployeeLastNameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone number cannot be empty.
        /// </summary>
        internal static string EmployeePhoneError {
            get {
                return ResourceManager.GetString("EmployeePhoneError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The employee role cannot be empty.
        /// </summary>
        internal static string EmployeeRoleError {
            get {
                return ResourceManager.GetString("EmployeeRoleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pnlLogin.
        /// </summary>
        internal static string LoginPanel {
            get {
                return ResourceManager.GetString("LoginPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pnl.
        /// </summary>
        internal static string PanelPrefix {
            get {
                return ResourceManager.GetString("PanelPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRANSFER TICKET.
        /// </summary>
        internal static string TransferTicket {
            get {
                return ResourceManager.GetString("TransferTicket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
